/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.4/userguide/building_java_projects.html in the Gradle documentation.
 */

 plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    // id("org.jetbrains.kotlin.jvm") version "1.9.10"
    // kotlin("jvm") version "1.9.20"

    kotlin("plugin.serialization") version "1.9.20"

    id("org.jetbrains.kotlin.jvm") version "1.5.31"
    // id("io.spring.gradle.plugin") version "1.0.11"

    

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}
group = "com.example"
version = "1.0"

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use the Kotlin JUnit 5 integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5")
    

    // Use the JUnit 5 integration.
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.9.3")

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    //Junit testing
    testImplementation("junit:junit:4.12")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:32.1.1-jre")

    implementation("io.ktor:ktor-server-netty:1.6.3")
    implementation("io.ktor:ktor-server-core:1.6.3")
    implementation("io.ktor:ktor-serialization:1.6.3")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.6.0")
    
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(19))
    }
}

application {
    // Define the main class for the application.
    mainClass.set("deliveryfee.AppKt")

}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

tasks.withType<Jar> {
    manifest {
        attributes("Main-Class" to "deliveryfee.AppKt")
        fatJar {
            archiveFileName.set("hibiki.jar") // Replace 'my-app-ktor.jar' with the desired filename for the JAR file
        }
    }
}

// ktor {
//     fatJar {
//         archiveFileName.set("fat.jar")
//     }
// }

