/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package deliveryfee

import kotlin.test.Test
import kotlin.test.assertNotNull
import kotlin.test.assertEquals


class AppTest {
    @Test fun testCalculationz() {
        val sum = calculateItemSurcharge(4)

        assertEquals(0, sum)
        assertNotNull(sum)
    }

    @Test fun appHasAGreeting1() {
        val sum2 = calculateItemSurcharge(4)

        assertEquals(0, sum2)
        assertNotNull(sum2)
    }


}


class AppTest1 {
    @Test fun appHasAGreeting() {
        val sum = calculateItemSurcharge(4)

        assertEquals(0, sum)
        assertNotNull(sum)
    }
}