/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package feeee

import kotlin.test.Test
import kotlin.test.assertNotNull
import kotlin.test.assertEquals

// https://github.com/woltapp/engineering-summer-intern-2023


class testEachFunctions {

val instCalc = Deliveryfee();

    @Test fun `calculateOrderSurcharge shoud be the difference between the cart value and 10€`() {
        val zero = instCalc.calculateOrderSurcharge(0)
        val one = instCalc.calculateOrderSurcharge(1)
        val small = instCalc.calculateOrderSurcharge(790)
        val just = instCalc.calculateOrderSurcharge(1000)
        val large = instCalc.calculateOrderSurcharge(1234)

        assertEquals(1000, zero)
        assertEquals(999, one)
        assertEquals(210, small)
        assertEquals(0, just)
        assertEquals(0, large)
        
    }

    //
    @Test fun DistanceFee() {
        val zero = instCalc.calculateDistanceFee(0)
        val small = instCalc.calculateDistanceFee(800)
        val just = instCalc.calculateDistanceFee(1000)
        val large = instCalc.calculateDistanceFee(2050)
        val large2 = instCalc.calculateDistanceFee(1700) 

        assertEquals(200, zero)
        assertEquals(200, small)
        assertEquals(200, just)
        assertEquals(500, large)
        assertEquals(400, large2)
        println(large2)
    }

    //
    @Test fun ItemSurcharge() {
        val zero = instCalc.calculateItemSurcharge(0)
        val small = instCalc.calculateItemSurcharge(1)
        val just = instCalc.calculateItemSurcharge(5)
        val large = instCalc.calculateItemSurcharge(7)
        val twelve = instCalc.calculateItemSurcharge(12)
        val superLarge = instCalc.calculateItemSurcharge(17)

        assertEquals(0, zero)
        assertEquals(0, small)
        assertEquals(50, just)
        assertEquals(150, large)
        assertEquals(400, twelve)
        assertEquals(770, superLarge)
      
    }


    //Final calc
    @Test fun finalCalculation() {
        // 
        val request = DeliveryRequest (
            cart_value = 790,
            delivery_distance = 2235,
            number_of_items = 4,
            time = "2021-10-12T13:00:00Z"
        )

        val deliveryFee = instCalc.calculateDeliveryFee(request)

        assertEquals(710, deliveryFee)

        // 
        val request2 = DeliveryRequest (
            cart_value = 0,
            delivery_distance = 0,
            number_of_items = 0,
            time = "2021-10-12T13:00:00Z"
        )
        val zero = instCalc.calculateDeliveryFee(request2)
        assertEquals(1200, zero)


         // Rush
         val request3 = DeliveryRequest (
            cart_value = 0,
            delivery_distance = 0,
            number_of_items = 0,
            time = "2023-11-10T17:00:00Z"
        )
        val RushHour = instCalc.calculateDeliveryFee(request3)
        // assertEquals(1200, RushHour)
        // println(RushHour)
 
    }
  


}


